### ISSUE TITLE
Consider making a no_std feature option

### ISSUE THREAD

**Issue by richardanaya** [ClickSimply/NoProto#1]
Would be nice to use no_proto in places were trying to be as minimal as possible (like web assembly)

**Comment by ClickSimply** [comment]
Will need to switch to [rjson](https://crates.io/crates/rjson), looks like the `rand` crate used for UUIDs and such already supports no_std.  Also it looks like `Vec` isn't really usable even with [core](https://doc.rust-lang.org/core/index.html), so we'd have to switch to `[u8]`.

I was planning on porting this library to Typescript after the Rust version was done.  Might make more sense to just compile it into WASM.  The changes above shouldn't be too difficult.

**Comment by richardanaya** [comment]
Exciting! use Vec from the alloc crate, it’s extremely minimal. no_std and
alloc make really minimal wasm.
