### ISSUE TITLE
Add comparison with Veriform

### ISSUE THREAD

**Issue by joseluis** [ClickSimply/NoProto#4]
It would be nice to add [Veriform](https://github.com/iqlusioninc/veriform) to the comparisons list.

**Comment by ClickSimply** [comment]
Interesting, it looks like Veriform has more in common with Serde than with many of the other projects.  There documentation is pretty sparse so I'm not 100% solid on the comparison table.

Seems like the two projects have pretty dramatically different goals.  I've pushed a comparison onto the main readme: https://github.com/ClickSimply/NoProto/blob/master/README.md
